#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
for ((i=1;i<=100;i++))
do
    if [[ $i%5 -eq 0 && $i%3 -eq 0 ]]; then
        echo "FizzBuzz"
    elif [[ $i%3 -eq 0 ]]; then
        echo "Fizz"
    elif [[ $i%5 -eq 0 ]]; then
        echo "Buzz"
    else
        echo "$i"
    fi
done