#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
i=1
while [ $i -lt 21 ]
do
    case $i in
    4)
        echo $i
        echo "bad luck from China";;
    9)
        echo $i
        echo "bad luck from Japan";;
    17)
        echo $i
        echo "bad luck from Italy";;
    esac
        echo $i
    ((i=i+1))
done