#!/usr/bin/env bash
# Nginx as user and config Nginx

pkill apache2
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo service nginx restart
