#!/usr/bin/env bash
# Nginx config
sudo service nginx stop
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
pkill apache2
sudo service nginx start
